---
- name: install gcc
  apt: name=gcc state=present
  sudo: yes

- name: install uwsgi server
  pip: name=uwsgi virtualenv={{ uwsgi_venv }} version=2.0
  sudo: yes

- name: configure app on uwsgi server
  template: src=uwsgi/app_uwsgi.ini dest={{ uwsgi_config_path }}/{{ uwsgi_app_ini }}
  sudo: yes
